### ISSUE TITLE
How to make sure the gateway starts healthily?

### ISSUE THREAD

**Issue by TAT-Hins** [Eugeny/tabby-connection-gateway#23]
I tried to use Docker compose file to start Tabby connection gateway and Tabby web service at the same time. Here is part of the contents of my current Docker Compose file.

``` yaml
services:
  tabby-gateway:
    image: ghcr.io/eugeny/tabby-connection-gateway:master
    ...

  tabby-web:
    image: ghcr.io/eugeny/tabby-web:latest
    ...
    depends_on:
      tabby-gateway:
        condition: service_started
      mariadb:
        condition: service_healthy
```

I would like to start the web container only when the gateway starts healthily, and therefore I would like to change the status of the gateway from `service_started` to `service_healthy`, just like what it is for the mariadb database.

Are there any scripts or commands to **do the health check** and make sure the gateway works well?
